// Department
export const DEPARTMENT_DATA_PENDING = 'DEPARTMENT_DATA_PENDING';
export const DEPARTMENT_DATA_FULLFIELD = 'DEPARTMENT_DATA_FULLFIELD';
export const DEPARTMENT_DATA_REJECTED = 'DEPARTMENT_DATA_REJECTED';